# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_IMAGE = "centos/7"

Vagrant.configure("2") do |config|

  config.vm.define "prometheus" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vbguest.installer_options = {allow_kernel_upgrade: true}
    subconfig.vm.hostname = "prometheus"
    subconfig.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "prod" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vbguest.installer_options = {allow_kernel_upgrade: true}
    subconfig.vm.hostname = "prod"
    subconfig.vm.network "private_network", ip: "192.168.33.20"
  end

end
