# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_IMAGE = "centos/7"

Vagrant.configure("2") do |config|

  config.vm.define "prometheus2" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vbguest.installer_options = {allow_kernel_upgrade: true}
    subconfig.vm.hostname = "prometheus2"
    subconfig.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "prod2" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vbguest.installer_options = {allow_kernel_upgrade: true}
    subconfig.vm.hostname = "prod2"
    subconfig.vm.network "private_network", ip: "192.168.33.21"
  end

end
